#
# 编写所有环境共用的配置
#
spring:
  application:
    name: PRODUCTS
  # 集成消息总线，配置rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    consul:
      host: localhost
      port: 8500
